# manually trigger the action to create a release draft
name: Draft Release (using embed)

env:
  NAME: helloworld
  INPUT_VERSION: ${{ github.event.inputs.version }}

# manually trigger in the actions tab
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (without v)"
        required: true
        default: "0.1.0"

jobs:
  build:
    name: Draft Release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Persist Version and Commit
        run: |
          go version
          timedatectl
          echo $INPUT_VERSION
          echo $INPUT_VERSION > version.txt
          echo $GITHUB_SHA
          echo $GITHUB_SHA > commit.txt
      - name: Build Linux
        run: env GOOS=linux GOARCH=amd64 go build -o ${NAME}-linux
      - name: UPX Linux
        uses: crazy-max/ghaction-upx@v2
        with:
          files: ${{env.NAME}}-linux

      - name: Build Linux arm
        # GOARM=6 (Raspberry Pi A, A+, B, B+, Zero) GOARM=7 (Raspberry Pi 2, 3)
        run: env GOARM=6 GOOS=linux GOARCH=arm go build -o ${NAME}-linux-arm
      - name: UPX Linux arm
        uses: crazy-max/ghaction-upx@v2
        with:
          files: ${{env.NAME}}-linux-arm

      - name: Build macOS amd64
        run: env GOOS=darwin GOARCH=amd64 go build -o ${NAME}-macos
      - name: UPX macOS amd64
        uses: crazy-max/ghaction-upx@v2
        with:
          files: ${{ env.NAME }}-macos

      - name: Build macOS arm64
        run: env GOOS=darwin GOARCH=arm64 go build -o ${NAME}-macos-arm
      # - name: UPX macOS arm64
      #   uses: crazy-max/ghaction-upx@v2
      #   with:
      #     files: ${{ env.NAME }}-macos-arm

      - name: Build Windows
        run: env GOOS=windows GOARCH=amd64 go build -o ${NAME}-windows.exe
      - name: UPX Windows
        uses: crazy-max/ghaction-upx@v2
        with:
          files: ${{ env.NAME }}-windows.exe

        # https://github.com/ncipollo/release-action
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.NAME }}-*"
          tag: v${{ github.event.inputs.version }}
          name: v${{ github.event.inputs.version }}
          body: Bugfixes and stability improvements.
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
