name: Watch Release

env:
  NAME: helloworld
  VERSION: "0.0.1"

on:
  push:
    branches:
      - main
      - master
    paths:
      - "version.txt"

jobs:
  build:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
      - name: Set variables
        run: |
          VER=$(cat version.txt | tr -d '\n')
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: Persist Version and Commit
        run: |
          go version
          timedatectl
          echo $GITHUB_SHA
          echo $GITHUB_SHA > commit.txt
          echo "${{github.event.commits[0].message}}"
      - name: Build Linux
        run: env GOOS=linux GOARCH=amd64 go build -o ${NAME}-linux
      - name: UPX Linux
        uses: crazy-max/ghaction-upx@v1.3.3
        with:
          file: ${{env.NAME}}-linux

      - name: Build Linux arm
        # GOARM=6 (Raspberry Pi A, A+, B, B+, Zero) GOARM=7 (Raspberry Pi 2, 3)
        run: env GOARM=6 GOOS=linux GOARCH=arm go build -o ${NAME}-linux-arm
      - name: UPX Linux arm
        uses: crazy-max/ghaction-upx@v1.3.3
        with:
          file: ${{env.NAME}}-linux-arm

      - name: Build macOS amd64
        run: env GOOS=darwin GOARCH=amd64 go build -o ${NAME}-macos
      - name: UPX macOS amd64
        uses: crazy-max/ghaction-upx@v1.3.3
        with:
          file: ${{ env.NAME }}-macos

      - name: Build macOS arm64
        run: env GOOS=darwin GOARCH=arm64 go build -o ${NAME}-macos-arm
      - name: UPX macOS arm64
        uses: crazy-max/ghaction-upx@v1.3.3
        with:
          file: ${{ env.NAME }}-macos-arm

      - name: Build Windows
        run: env GOOS=windows GOARCH=amd64 go build -o ${NAME}-windows.exe
      - name: UPX Windows
        uses: crazy-max/ghaction-upx@v1.3.3
        with:
          file: ${{ env.NAME }}-windows.exe

      # https://github.com/marketplace/actions/tag-and-release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: ${{ env.NAME }} v${{ env.VERSION }}
          body: |
            ${{github.event.commits[0].message}}
          draft: false
          prerelease: false

      # https://github.com/actions/upload-release-asset
      - name: Upload Release macOS amd64
        id: upload-release-asset-macos
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.NAME }}-macos
          asset_name: ${{ env.NAME }}-macos
          asset_content_type: application/octet-stream
      - name: Upload Release macOS arm64
        id: upload-release-asset-macos-arm
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.NAME }}-macos-arm
          asset_name: ${{ env.NAME }}-macos-arm
          asset_content_type: application/octet-stream
      - name: Upload Release Linux
        id: upload-release-asset-linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.NAME }}-linux
          asset_name: ${{ env.NAME }}-linux
          asset_content_type: application/octet-stream
      - name: Upload Release Linux Arm
        id: upload-release-asset-linux-arm
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.NAME }}-linux-arm
          asset_name: ${{ env.NAME }}-linux-arm
          asset_content_type: application/octet-stream
      - name: Upload Release Windows
        id: upload-release-asset-windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.NAME }}-windows.exe
          asset_name: ${{ env.NAME }}-windows.exe
          asset_content_type: application/octet-stream
