# .github/workflows/release.yaml
name: Release

env:
  NAME: helloworld

# manually trigger in the actions tab
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: '0.1.0'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build Linux
      run: env GOOS=linux GOARCH=amd64 go build -o ${NAME}-linux
      
    - name: UPX Linux
      uses: crazy-max/ghaction-upx@v1.3.3
      with:
        file: ${{env.NAME}}-linux

    - name: Build macOS
      run: env GOOS=darwin GOARCH=amd64 go build -o ${NAME}-macos

    - name: UPX macOS
      uses: crazy-max/ghaction-upx@v1.3.3
      with:
        file: ${{env.NAME}}-macos

    
    # https://github.com/marketplace/actions/tag-and-release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.version }}
        release_name: ${{ github.event.inputs.version }}
        body: |
          Bugfixes and stability improvements.
        draft: true
        prerelease: false

# misc
# https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables
# ${{ runner.OS }}
# ${{ github.event.inputs.version }}

